# Generated by Django 5.0.3 on 2025-06-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_apikey_updated_on_alter_apikey_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(default='/logo.jpeg', null=True),
        ),
    ]
