# Generated by Django 5.0.3 on 2024-09-09 11:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0004_alter_roadmaptask_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapcategory',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadmapcategory',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
